import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { claudeHistory, claudeTranscriptFor } from '../src/brain/history.js';
import { projectFolder } from '../src/brain/transcripts.js';

const ID = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';
const T = (n: number) => `2026-01-01T00:00:${String(n).padStart(2, '0')}.000Z`;

/** Lines shaped like Claude Code's own: one content block per assistant line, bookkeeping lines around. */
const user = (content: unknown, n: number, extra: object = {}) =>
  ({ type: 'user', isSidechain: false, timestamp: T(n), message: { role: 'user', content }, ...extra });
const asst = (id: string, block: object, n: number, extra: object = {}) =>
  ({ type: 'assistant', isSidechain: false, timestamp: T(n), message: { id, role: 'assistant', content: [block] }, ...extra });
const text = (t: string) => ({ type: 'text', text: t });
const tool = (name: string) => ({ type: 'tool_use', id: `toolu_${name}`, name, input: {} });
const result = (id: string) => [{ type: 'tool_result', tool_use_id: id, content: 'output' }];

function write(lines: (object | string)[]): string {
  const dir = mkdtempSync(join(tmpdir(), 'angelia-history-'));
  const p = join(dir, `${ID}.jsonl`);
  writeFileSync(p, lines.map((l) => (typeof l === 'string' ? l : JSON.stringify(l))).join('\n') + '\n');
  return p;
}

test('one assistant message split over several lines with the same id is one item; thinking and tool results are not shown', () => {
  const p = write([
    { type: 'permission-mode', permissionMode: 'default' },
    user('Fix the build', 1),
    { type: 'attachment', attachment: { type: 'hook' } },
    asst('msg_1', { type: 'thinking', thinking: 'secret reasoning', signature: 'x' }, 2),
    asst('msg_1', text('Looking.'), 3),
    asst('msg_1', tool('Bash'), 4),
    asst('msg_1', tool('Read'), 5),
    user(result('toolu_Bash'), 6),
    user(result('toolu_Read'), 7),
    asst('msg_1', tool('Bash'), 8),
    asst('msg_2', { type: 'thinking', thinking: 'more', signature: 'y' }, 9),
    asst('msg_2', text('Done.'), 10),
    asst('msg_2', text('Tests pass.'), 11),
    { type: 'system', subtype: 'turn_duration', durationMs: 1 },
  ]);
  assert.deepEqual(claudeHistory(p), {
    items: [
      { role: 'user', text: 'Fix the build', at: T(1) },
      { role: 'assistant', text: 'Looking.', at: T(2), tools: ['Bash', 'Read'] },
      { role: 'assistant', text: 'Done.\n\nTests pass.', at: T(9) },
    ],
    more: false,
  });
  assert.doesNotMatch(JSON.stringify(claudeHistory(p)), /secret reasoning/);
});

test('an assistant message with tools and no text still counts; one with only thinking does not', () => {
  const p = write([
    user('go', 1),
    asst('msg_1', tool('Grep'), 2),
    asst('msg_2', { type: 'thinking', thinking: 'hmm', signature: 's' }, 3),
  ]);
  assert.deepEqual(claudeHistory(p).items, [
    { role: 'user', text: 'go', at: T(1) },
    { role: 'assistant', text: '', at: T(2), tools: ['Grep'] },
  ]);
});

test('sidechain, meta, compact summaries and wrapper-only lines are left out; a slash command shows as its command', () => {
  const p = write([
    user('<local-command-caveat>Caveat: generated by local commands.</local-command-caveat>', 1, { isMeta: true }),
    user('<command-name>/compact</command-name>\n<command-message>compact</command-message>\n<command-args></command-args>', 2),
    user('<local-command-stdout>Compacted</local-command-stdout>', 3),
    user('Summary of the earlier conversation', 4, { isCompactSummary: true, isVisibleInTranscriptOnly: true }),
    user('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>', 5),
    user('Subagent prompt', 6, { isSidechain: true }),
    asst('msg_s', text('Subagent reply'), 7, { isSidechain: true }),
    user('Skill body loaded for the model', 8, { isMeta: true }),
    user('<system-reminder>internal</system-reminder>', 9),
    user('<system-reminder>internal</system-reminder>\nWhat changed?', 10),
    user('<task-notification><task-id>1</task-id><status>completed</status></task-notification>', 11),
    user([text('Look at this'), { type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'AAAA' } }], 12),
    asst('msg_1', text('Seen.'), 13),
  ]);
  assert.deepEqual(claudeHistory(p).items.map((i) => [i.role, i.text]), [
    ['user', '/compact'],
    ['user', '/model opus'],
    ['user', 'What changed?'],
    ['user', 'Look at this'],
    ['assistant', 'Seen.'],
  ]);
});

test('a malformed line is skipped, not thrown', () => {
  const p = write([
    user('first', 1),
    '{"type":"user","message":{"content":"trunc',
    'not json at all',
    '',
    asst('msg_1', text('reply'), 2),
  ]);
  assert.deepEqual(claudeHistory(p).items.map((i) => i.text), ['first', 'reply']);
});

test('limit keeps the newest messages, oldest first, and more says older ones exist', () => {
  const lines: object[] = [];
  for (let i = 0; i < 10; i++) {
    lines.push(user(`q${i}`, i * 2));
    lines.push(asst(`msg_${i}`, text(`a${i}`), i * 2 + 1));
  }
  const p = write(lines);
  const page = claudeHistory(p, { limit: 3 });
  assert.deepEqual(page.items.map((i) => i.text), ['a8', 'q9', 'a9']);
  assert.equal(page.more, true);
  assert.deepEqual(claudeHistory(p, { limit: 20 }).more, false);
  assert.equal(claudeHistory(p).items.length, 20);
  assert.equal(claudeHistory(p, { limit: 20 }).items[0].text, 'q0');
});

test('a missing file is an empty page', () => {
  assert.deepEqual(claudeHistory(join(tmpdir(), 'angelia-no-such-dir', `${ID}.jsonl`)), { items: [], more: false });
});

test('the transcript under the cwd\'s own folder wins over a larger copy elsewhere; else the largest copy; else none', () => {
  const root = mkdtempSync(join(tmpdir(), 'angelia-projects-'));
  const cwd = mkdtempSync(join(tmpdir(), 'angelia-cwd-'));
  assert.equal(claudeTranscriptFor(cwd, ID, root), undefined);

  mkdirSync(join(root, '-elsewhere-small'));
  writeFileSync(join(root, '-elsewhere-small', `${ID}.jsonl`), '{}\n');
  mkdirSync(join(root, '-elsewhere-big'));
  writeFileSync(join(root, '-elsewhere-big', `${ID}.jsonl`), '{}\n{}\n{}\n');
  assert.equal(claudeTranscriptFor(cwd, ID, root), join(root, '-elsewhere-big', `${ID}.jsonl`));

  const here = join(root, projectFolder(cwd), `${ID}.jsonl`);
  mkdirSync(join(root, projectFolder(cwd)));
  writeFileSync(here, '');
  assert.equal(claudeTranscriptFor(cwd, ID, root), join(root, '-elsewhere-big', `${ID}.jsonl`), 'an empty file is not the conversation');
  writeFileSync(here, '{}\n');
  assert.equal(claudeTranscriptFor(cwd, ID, root), here);
});

test('history: a transcript over the byte cap is read from its end, and says older messages exist', () => {
  const dir = mkdtempSync(join(tmpdir(), 'angelia-history-cap-'));
  const path = join(dir, 's.jsonl');
  const lines = Array.from({ length: 50 }, (_, n) => JSON.stringify({ type: 'user', message: { role: 'user', content: `message ${n} ${'x'.repeat(100)}` } }));
  writeFileSync(path, lines.join('\n') + '\n');
  const page = claudeHistory(path, { maxBytes: 1000 });
  assert.equal(page.more, true);
  assert.ok(page.items.length > 0 && page.items.length < 50);
  assert.match(page.items.at(-1)!.text, /^message 49 /);
  assert.ok(page.items.every((i) => /^message \d+ x+$/.test(i.text)), 'no half line at the cut');
});

test('history: a cut that lands on a line start keeps that whole line', () => {
  const dir = mkdtempSync(join(tmpdir(), 'angelia-history-edge-'));
  const path = join(dir, 's.jsonl');
  const last = JSON.stringify({ type: 'user', message: { role: 'user', content: 'the last one' } });
  writeFileSync(path, JSON.stringify({ type: 'user', message: { role: 'user', content: 'older' } }) + '\n' + last + '\n');
  const page = claudeHistory(path, { maxBytes: Buffer.byteLength(last) + 1 });
  assert.deepEqual(page.items.map((i) => i.text), ['the last one']);
  assert.equal(page.more, true);
});

test('older pages: the cursor walks back to the first message, in order, with nothing lost or twice', () => {
  // Multi-byte text (Hebrew, emoji) so a byte cursor that counted characters would land mid-line.
  const lines: object[] = [];
  for (let i = 0; i < 12; i++) {
    lines.push(user(`שאלה ${i} 🙂`, i * 3));
    lines.push(asst(`msg_${i}`, text(`answer ${i} ✓`), i * 3 + 1), asst(`msg_${i}`, tool('Bash'), i * 3 + 2));
    lines.push(user(result('toolu_Bash'), i * 3 + 2));
  }
  const p = write(lines);
  const all = claudeHistory(p, { limit: 1000 });
  assert.equal(all.items.length, 24);
  assert.equal(all.more, false);
  assert.equal(all.cursor, undefined);
  const seen: string[] = [];
  let page = claudeHistory(p, { limit: 5 });
  for (let n = 0; n < 10; n++) {
    seen.unshift(...page.items.map((i) => i.text));
    if (!page.more) break;
    assert.ok(page.cursor, 'a page with more has a cursor');
    page = claudeHistory(p, { limit: 5, before: page.cursor });
  }
  assert.deepEqual(seen, all.items.map((i) => i.text));
  assert.equal(page.more, false);
  // A cursor that is not one of ours is ignored, not trusted.
  assert.deepEqual(claudeHistory(p, { limit: 5, before: '../etc' }).items, claudeHistory(p, { limit: 5 }).items);
});

test('older pages work past the byte cap too: a cut page still has a cursor', () => {
  const lines: object[] = [];
  for (let i = 0; i < 40; i++) lines.push(user(`message ${i} ${'x'.repeat(200)}`, i % 60));
  const p = write(lines);
  const first = claudeHistory(p, { limit: 1000, maxBytes: 3000 });
  assert.equal(first.more, true);
  assert.ok(first.items.length < 40);
  const older = claudeHistory(p, { limit: 1000, maxBytes: 3000, before: first.cursor });
  assert.ok(older.items.length > 0);
  assert.equal(older.items.at(-1)?.text.split(' ')[1], String(Number(first.items[0].text.split(' ')[1]) - 1), 'the older page ends right before the newer one starts');
});

test('history: a run of wrapper blocks with text after them is checked in linear time', async () => {
  const { wrapperOnly } = await import('../src/brain/history.js');
  const t0 = Date.now();
  // 28 blocks took 8.5 s with the old regex, 500 never ended.
  assert.equal(wrapperOnly('<system-reminder>a</system-reminder>'.repeat(5000) + 'x'), false);
  assert.ok(Date.now() - t0 < 1000, `${Date.now() - t0} ms`);
  assert.equal(wrapperOnly('<system-reminder>a</system-reminder>\n<task-notification>b</task-notification>\n'), true);
  assert.equal(wrapperOnly('typed <system-reminder>a</system-reminder>'), false);
  assert.equal(wrapperOnly('<other>a</other>'), false);
});
